### ISSUE TITLE
特殊文字ℎがhに変換されない

### ISSUE THREAD

**Issue by suzukeng** [ppputtyo/ToNormalCode#5]
特殊文字ℎがhに変換されずそのままℎと変換されてしまいます。
具体的には以下の問題文で翻訳を行った際に正しい変換が行われませんでした。
[https://codeforces.com/contest/1695/problem/A](url)
issueをあまり書き慣れてないのでバグ報告の仕方間違っていたりしたら教えてくださると嬉しいです。

**Comment by ppputtyo** [comment]
ご報告ありがとうございます。
私の環境でもバグの再現ができ、原因が究明できたので修正します。
